### ISSUE TITLE
NHLOutput.csv

### ISSUE THREAD

**Issue by SamuelLachance** [JNoel71/NHL-Pre-Game-Prediction-Model#1]
Traceback (most recent call last):
  File "D:\pred\NHL-Pre-Game-Prediction-Model\ModelCreationNHLMW.py", line 557, in <module>
    main(False,"LR")
  File "D:\pred\NHL-Pre-Game-Prediction-Model\ModelCreationNHLMW.py", line 530, in main
    newTrainDF = pd.read_csv("NHLOutput.csv")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'NHLOutput.csv'

i have run DataCreation and ScrapeGames before running model creation , but the 2 previous file did not create NHLOutput.csv , theyr created NHLData.csv , what i'm doing wrong ?

**Comment by JNoel71** [comment]
It has to do with the call of the main method. At the bottom of the ModelCreationNHLMW.py it says main(False,"LR"), the boolean at the beginning determines whether NHLOutput.csv is created. So simply change False to True.

**Comment by SamuelLachance** [comment]
thanks
